# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodeInterface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nodeInterface.proto',
  package='nodeInterface',
  syntax='proto3',
  serialized_pb=_b('\n\x13nodeInterface.proto\x12\rnodeInterface\">\n\x07\x43ommand\x12\x12\n\ntxInterval\x18\x01 \x01(\x02\x12\x10\n\x08msgBytes\x18\x02 \x01(\x0c\x12\r\n\x05\x63mdId\x18\x03 \x01(\r\"\xef\x01\n\rNodeThreadMsg\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.nodeInterface.NodeThreadMsg.NodeMsgType\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x10\n\x08\x63mdRelay\x18\x03 \x01(\x0c\x12$\n\x04\x63mds\x18\x04 \x03(\x0b\x32\x16.nodeInterface.Command\x12\x12\n\nlinkStatus\x18\x05 \x03(\r\x12\x11\n\trcvdBytes\x18\x06 \x01(\x0c\x12\x11\n\tdataBlock\x18\x07 \x01(\x0c\"!\n\x0bNodeMsgType\x12\x08\n\x04NODE\x10\x00\x12\x08\n\x04\x43OMM\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_NODETHREADMSG_NODEMSGTYPE = _descriptor.EnumDescriptor(
  name='NodeMsgType',
  full_name='nodeInterface.NodeThreadMsg.NodeMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMM', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=309,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_NODETHREADMSG_NODEMSGTYPE)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='nodeInterface.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txInterval', full_name='nodeInterface.Command.txInterval', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgBytes', full_name='nodeInterface.Command.msgBytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdId', full_name='nodeInterface.Command.cmdId', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=100,
)


_NODETHREADMSG = _descriptor.Descriptor(
  name='NodeThreadMsg',
  full_name='nodeInterface.NodeThreadMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='nodeInterface.NodeThreadMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nodeInterface.NodeThreadMsg.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdRelay', full_name='nodeInterface.NodeThreadMsg.cmdRelay', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmds', full_name='nodeInterface.NodeThreadMsg.cmds', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linkStatus', full_name='nodeInterface.NodeThreadMsg.linkStatus', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rcvdBytes', full_name='nodeInterface.NodeThreadMsg.rcvdBytes', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataBlock', full_name='nodeInterface.NodeThreadMsg.dataBlock', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODETHREADMSG_NODEMSGTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=342,
)

_NODETHREADMSG.fields_by_name['type'].enum_type = _NODETHREADMSG_NODEMSGTYPE
_NODETHREADMSG.fields_by_name['cmds'].message_type = _COMMAND
_NODETHREADMSG_NODEMSGTYPE.containing_type = _NODETHREADMSG
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['NodeThreadMsg'] = _NODETHREADMSG

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'nodeInterface_pb2'
  # @@protoc_insertion_point(class_scope:nodeInterface.Command)
  ))
_sym_db.RegisterMessage(Command)

NodeThreadMsg = _reflection.GeneratedProtocolMessageType('NodeThreadMsg', (_message.Message,), dict(
  DESCRIPTOR = _NODETHREADMSG,
  __module__ = 'nodeInterface_pb2'
  # @@protoc_insertion_point(class_scope:nodeInterface.NodeThreadMsg)
  ))
_sym_db.RegisterMessage(NodeThreadMsg)


# @@protoc_insertion_point(module_scope)
